create table TBL_MANAGEMENT(
	MANAGEMENT_ID		NUMBER(19,0) primary key,
	CONTRIBUTION_ID		NUMBER(19,0),
	ARTICLE_ID		NUMBER(19,0),
	SERVICE_ID		NUMBER(19,0),
	LOGIN_ID		NUMBER(19,0),
	STATUS		CHAR,
	VOTE		NUMBER(19,0),
	START_DATE		DATE,
	END_DATE		DATE,
	LIMIT_DATE		DATE,
	SUB_TASK_NO		NUMBER(1,0),
	COUNT_SUB_TASK		NUMBER(1,0)
);

create table TBL_VISITOR_LOGIN(
	LOGIN_ID		NUMBER(19,0) primary key,
	USER_NO		VARCHAR(32),
	ENAME		VARCHAR(256),
	JNAME		VARCHAR(256),
	LOGIN_PASSWORD		VARCHAR(32),
	EMAIL		VARCHAR(256)
);

create table TBL_AUTHORITY(
	AUTHORITY_ID		NUMBER(19,0) primary key,
	AUTHORITY_ENAME		VARCHAR(64),
	AUTHORITY_JNAME		VARCHAR(64)
);

create table TBL_SERVICE(
	SERVICE_ID		NUMBER(19,0) primary key,
	AUTHORITY_ID		NUMBER(19,0),
	SERVICE_ENAME		VARCHAR(256),
	SERVICE_JNAME		VARCHAR(256)
);

create table TBL_ARTICLE(
	ARTICLE_ID		NUMBER(19,0) primary key,
	ARTICLE_ENAME		VARCHAR(256),
	ARTICLE_JNAME		VARCHAR(256),
	ARTICLE_ESUBTITLE		VARCHAR(256),
	ARTICLE_JSUBTITLE		VARCHAR(256),
	EABSTRACT		VARCHAR(4000),
	JABSTRACT		VARCHAR(4000)
);

create table TBL_CONTRIBUTION(
	CONTRIBUTION_ID		NUMBER(19,0) primary key,
	LOGIN_ID		NUMBER(19,0),
	FIELD_ID		NUMBER(19,0),
	CONTRIBUTION_FILE		CHAR,
	ENGLISH_TITLE		VARCHAR(256),
	ENGLISH_SUB_TITLE		VARCHAR(256),
	JAPANESE_TITLE		VARCHAR(256),
	JAPANESE_SUB_TITLE		VARCHAR(256),
	EABSTRACT		VARCHAR(4000),
	JABSTRACT		VARCHAR(4000),
	CONTENTS_LEAVES		NUMBER(19,0),
	DEPRINT		NUMBER(19,0),
	WRITER_COUNT		NUMBER(19,0),
	KEYWORD_COUNT		NUMBER(19,0),
	CONTRIBUTION_FILE_NAME		VARCHAR(1024),
	TEMP_DATE		DATE,
	RECEIPT_DATE		DATE
);

create table TBL_CONTRIBUTOR(
	CONTRIBUTOR_ID		NUMBER(19,0) primary key,
	LOGIN_ID		NUMBER(19,0),
	CONTACT_LANGUAGE		CHAR,
	ZIP_CODE		VARCHAR(8),
	ADDRESS		VARCHAR(1024),
	TELEPHONE_NUMBER		VARCHAR(32),
	EXTENSION		VARCHAR(8),
	FAX_NUMBER		VARCHAR(32),
	KANA_NAME		VARCHAR(256),
	COUNTRY_NAME		VARCHAR(64),
	REMARK		VARCHAR(4000),
	REMARK1		VARCHAR(4000)
);

create table TBL_FILE(
	FILE_ID		NUMBER(19,0) primary key,
	CONTRIBUTION_ID		NUMBER(19,0),
	FILE_NAME		VARCHAR(256),
	FILE_PATH		VARCHAR(256),
	FILE_SIZE		NUMBER(19,0)
);

create table TBL_KEYWORD(
	KEYWORD_ID		NUMBER(19,0) primary key,
	KEYWORD_ENAME		VARCHAR(256),
	KEYWORD_JNAME		VARCHAR(256),
	CONTRIBUTION_ID		NUMBER(19,0)
);

create table TBL_AUTHOR(
	AUTHOR_ID		NUMBER(19,0) primary key,
	CONTRIBUTION_ID		NUMBER(19,0),
	BELONG_ID		NUMBER(19,0),
	SECOND_ENAME		VARCHAR(256),
	FIRST_ENAME		VARCHAR(256),
	SECOND_JNAME		VARCHAR(256),
	FIRST_JNAME		VARCHAR(256),
	SECOND_KANA		VARCHAR(256),
	FIRST_KANA		VARCHAR(256),
	AUTHOR_EMAIL		VARCHAR(256),
	AUTHOR_URL		VARCHAR(256)
);

create table TBL_BELONG(
	BELONG_ID		NUMBER(19,0) primary key,
	BELONG_ENAME		VARCHAR(256),
	BELONG_JNAME		VARCHAR(256),
	BELONG_KANA		VARCHAR(256),
	BELONG_EADDRESS		VARCHAR(1024),
	BELONG_JADDRESS		VARCHAR(1024),
	BELONG_ZIP_CODE		VARCHAR(8),
	BELONG_URL		VARCHAR(1024)
);

create table TBL_RECEIPT_VOTE(
	RECEIPT_ID		NUMBER(19,0) primary key,
	RECEIPT_NOTICE_FLG		CHAR,
	RECEIPT_DATE		DATE
);

create table TBL_JUDGE_VOTE(
	JUDGE_ID		NUMBER(19,0) primary key,
	MANUSCRIPT_EVALUATION_CD		CHAR,
	RE_JUDGE_READ		CHAR,
	TO_EDITORIAL_COMMITTEE_COMMENT		VARCHAR(4000),
	SKIL_EVALUATION_CD		CHAR,
	TO_AUTHOR_COMMENT_1		VARCHAR(4000),
	TO_AUTHOR_COMMENT_2		VARCHAR(4000)
);

create table TBL_EXAMINATION_VOTE(
	EXAMINATION_ID		NUMBER(19,0) primary key,
	RESULT_CD		CHAR,
	REASON_CONTENTS		VARCHAR(4000),
	TO_JUDGEMENT_CD		CHAR,
	TO_AUTHORC_CD		CHAR
);

create table TBL_DECISION_VOTE(
	DECISION_ID		NUMBER(19,0) primary key,
	DECISION_FLG		CHAR,
	RE_DESITION		VARCHAR(4000)
);

create table TBL_NOTICE_VOTE(
	NOTICE_ID		NUMBER(19,0) primary key,
	NOTICE_KIND		CHAR,
	LOGIN_ID		NUMBER(19,0),
	TO_EMAIL		VARCHAR(256),
	CC_EMAIL		VARCHAR(256),
	BCC_EMAIL		VARCHAR(256),
	SUBJECT		VARCHAR(256),
	CONTENTS		VARCHAR(4000),
	MANAGEMENT_ID		NUMBER(19,0)
);

create table TBL_EDITOR(
	EDITOR_ID		NUMBER(19,0) primary key,
	LOGIN_ID		NUMBER(19,0),
	AUTHORITY_ID		NUMBER(19,0),
	FIELD_ID		NUMBER(19,0),
	TAKING_CHARGE_COUNT		NUMBER(19,0),
	ACCUMULATION_COUNT		NUMBER(19,0)
);

create table TBL_FIELD(
	FIELD_ID		NUMBER(19,0) primary key,
	FIELD_ENAME		VARCHAR(256),
	FIELD_JNAME		VARCHAR(256)
);

create table SEQUENCE(
	NAME		VARCHAR(16) primary key,
	SEQ		NUMBER(19,0)
);

