all:
	mkdir -p lib bin
	cd src/ctl;make
	cd Paxos;make
	cd adm;make
clean:
	cd src/ctl;make clean
	cd Paxos;make clean
	cd adm;make clean
install:
#	cd src/ctl/db;make install
#	cd Paxos;make install
#	cd adm;make install
